### PR TITLE
[DEV-7809] Agency slugs

### PR DESCRIPTION
**Pull request by emily-brents**
**Description:**
Adds `agency_slug` field to the `/api/v2/references/toptier_agencies/` endpoint to be used by frontend to create links to new Agency v2 profile page.

**Technical details:**
`agency_slug` is based on the name of the toptier agency, all in lowercase and with the spaces replaced by `-`.

**Requirements for PR merge:**

1. [X] Unit & integration tests updated
2. [X] API documentation updated
3. [ ] Necessary PR reviewers:
    - [ ] Backend
    - [x] Frontend
4. [N/A] Matview impact assessment completed
5. [X] Frontend impact assessment completed
6. [X] Data validation completed
7. [N/A] Appropriate Operations ticket(s) created
8. [X] Jira Ticket [DEV-7809](https://federal-spending-transparency.atlassian.net/browse/DEV-7809):
    - [X] Link to this Pull-Request
    - [X] Performance evaluation of affected (API | Script | Download)
    - [X] Before / After data comparison

**Area for explaining above N/A when needed:**
```
```

### CODE REVIEW

**Review by ebdabbs — APPROVED** [review]
API contract change approved

**Comment by emily-brents** [comment]
> Since the point of the slug is to be used for URLs do you know if there will be any issues with an agency such as `U.S. International Development Finance Corporation` which has a slug of `u.s.-international-development-finance-corporation`? Wondering if any characters need to be removed from the slug.

Periods are usually "unreserved" characters in a URL as far as I know, so it shouldn't cause an issue.

**Comment by collinwr** [comment]
> > Since the point of the slug is to be used for URLs do you know if there will be any issues with an agency such as `U.S. International Development Finance Corporation` which has a slug of `u.s.-international-development-finance-corporation`? Wondering if any characters need to be removed from the slug.
> 
> Periods are usually "unreserved" characters in a URL as far as I know, so it shouldn't cause an issue.

Hey Emily, I took a look at the `toptier_agencies` table and saw quite a few other special characters in the `agency_name` column. Here are some examples.
```
National Commission on Military, National, and Public Service
Treasury FMS/FO/FASD/IFB
Corps of Engineers - Civil Works
Other (Listed Under Department of State)
```
Can you work with frontend to make sure that the resulting slug from these names meet their needs?

**Review by ebdabbs — APPROVED** [review]
API contract changes approved

**Review by collinwr — APPROVED** [review]
Approved

**Pull request merged**
