### PR TITLE
Update CodeClimate Rules

### PR DESCRIPTION
**Pull request by dpb-bah**
Simply update CC rules more matching the standard of the repo.

- [ ] Full consensus on agreeing what should change

### CODE REVIEW

**Review by collinwr — APPROVED** [review]
Cool!

**Comment by dporth-frb** [comment]
"files.trimTrailingWhitespace": true,
    "editor.tabSize": 4,
    "editor.detectIndentation": false,
    // Extension settings
    "python.linting.lintOnSave": true,
    "python.linting.pylintEnabled": false,
    "python.formatting.provider": "black",
    "editor.formatOnSave": false,  // enable per language
    "[python]": {
        "editor.defaultFormatter": "ms-python.python",
        "editor.formatOnSave": true,
    },
    "editor.defaultFormatter": "ms-python.black-formatter",
    "auto-rename-tag.activationOnLanguage": [
        "xml"
    ],
    "autoDocstring.docstringFormat": "google",
    "python.linting.flake8Enabled": true,
    "flake8.args": [
        "--max-line-length=120",
        "--ignore=E402,F841,F401,E302,E305",
        "--select=C,E,F,W,B,B950",
        "--exclude:.venv,build,usaspending_api.egg-info,usaspending_api/*/migrations/*",
        "--ignore=E501,W503,E203,F541"
    ],
    "python.linting.flake8Args": [
        "--max-line-length=120",
        "--ignore=E402,F841,F401,E302,E305",
        "--select=C,E,F,W,B,B950",
        "--exclude:.venv,build,usaspending_api.egg-info,usaspending_api/*/migrations/*",
        "--ignore=E501,W503,E203,F541"
    ],
    "black-formatter.args": [
        "--line-length", "120",
        "--target-version", "py37",
        "--exclude", "'/(\\.git|\\.venv|venv|migrations)/'"
    ],
    "python.formatting.blackArgs": [
        "--line-length", "120",
        "--target-version", "py37",
        "--exclude", "'/(\\.git|\\.venv|venv|migrations)/'"
    ],
    "[json]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },

**Comment by dporth-frb** [comment]
"extensions": [
        "aaron-bond.better-comments",
        "augustocdias.tasks-shell-input", // Required to extend inputs property so that it supports the command property, some tasks require commands like list all migrations by app.
        // "batisteo.vscode-django",
        "bierner.markdown-shiki", // Highlights code in markdown preview to match the colors in text editor
        "christian-kohler.path-intellisense", // Autocompletes filenames
        "clemenspeters.format-json", // Formats JSON file contents
        "cweijan.vscode-database-client2", // Connect to databases from VSCode
        // "donjayamanne.python-environment-manager",
        "eamodio.gitlens", // Tracks git changes
        // "ecmel.vscode-html-css",
        "ericsia.pythonsnippets3", // Auto suggestion for Python3 syntax
        // "njqdev.vscode-python-typehint", // Is this really needed since I already have pythonsnippets3
        "formulahendry.auto-rename-tag", // Auto updates closing tag of the tag being editted
        "formulahendry.code-runner", // Ability to run highlighted code
        // "github.remotehub",
        "grapecity.gc-excelviewer", // Edit Excel spreadsheets and CSV files in Visual Studio Code
        "gruntfuggly.todo-tree", // Easily manage TODOs
        "gurumukhi.selected-lines-count",
        // "hbenl.vscode-test-explorer",
        "johnpapa.vscode-peacock", // Change color of VSCode window
        // "littlefoxteam.vscode-python-test-adapter",
        "mechatroner.rainbow-csv", // Auto, syntax color highlighter for csv files
        "mhutchie.git-graph",
        "mikestead.dotenv", // .env syntax color highlighter
        "ms-azuretools.vscode-docker",
        "ms-python.black-formatter", // Auto formats Python code to meet PEP 8 standards
        "ms-python.flake8", // A line wrapper that covers style, syntax, and complexity
        // "ms-python.isort",
        "ms-python.python",
        "ms-python.vscode-pylance",
        "ms-vscode-remote.remote-containers",
        "ms-vscode.cpptools",
        "ms-vscode.remote-repositories",
        "ms-vscode.test-adapter-converter",
        "ms-vsliveshare.vsliveshare", // Share screen
        // "naumovs.color-highlight", // css/html syntax color highlighter
        "njpwerner.autodocstring",
        "oderwat.indent-rainbow",
        "redhat.vscode-yaml",
        // "thiscodeworks.savecode",
        "visualstudioexptteam.intellicode-api-usage-examples", // Browse code that's similar to yours
        "visualstudioexptteam.vscodeintellicode",
        "yzhang.markdown-all-in-one"
    ],

**Comment by dporth-frb** [comment]
exclude: /(\.git|\.venv|venv|migrations)/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: debug-statements
    -   id: flake8
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        language_version: python3.8

**Comment by dporth-frb** [comment]
version: "2"

languages:
  Python: true
  Javascript: true

checks:
  argument-count:
    enabled: true
    config:
      threshold: 6
  complex-logic:
    enabled: true
    config:
      threshold: 8
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 15
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 45
  nested-control-flow:
    enabled: true
    config:
      threshold: 5
  return-statements:
    enabled: true
    config:
      threshold: 3
  similar-code:
    enabled: false

engines:
  pep8:
    enabled: true
    checks:
      # Disable line length (> 79) check
      E501:
        enabled: false
      # Disable Line break occurred before a binary operator
      W503:
        enabled: false
      # Disable Whitespace before ':'
      E203:
        enabled: false
  radon:
    enabled: true
    config:
      python_version: 3
      threshold: "D"

ratings:
  paths:
  - "**.py"

exclude_paths:
  - "*/site-packages/*"
  - "usaspending_api/api_contracts/*"
  - "usaspending_api/api_docs/*"
  - "usaspending_api/*/migrations/*"
  - "usaspending_api/*/tests/*"
  - "usaspending_api/static_doc_files/js/*"

**Review by DKeele23 — APPROVED** [review]

**Comment by dporth-frb** [comment]
@dpb-bah This PR has been open for a long time, what's the status of it?

**Comment by dporth-frb** [comment]
After asking @dpb-bah about this PR, we are  closing PR as it's very stale.

> oh boy that ol’ thing (Dec 13, 2022). The latest status of that guy is…
https://data-transparency-bfs.slack.com/archives/CE5T3SLUD/p1670949122242769?thread_ts=1669066095.335389&cid=CE5T3SLUD
(cc’ing 
[@Danny Martin](https://data-transparency-bfs.slack.com/team/U01EHK39A7N)
 to appreciate the throwback)
No one has discussed it since. Considering that, I dont mind if it’s closed. I’d suggest going through with it if CC is still a pain at times on USAS.

**Pull request closed without merging**
