### PR TITLE
Staging -> Dev Hotfix downmerge

### PR DESCRIPTION
**Pull request by tony-sappe**
Downmerge hotfix to update an outdated constraint on the FABS table

### CODE REVIEW

**Comment by BrianZito** [comment]
Why is this needed?

**Comment by tony-sappe** [comment]
> Why is this needed?

Every time a PR "skips" a lower env it needs to propagate down from the "higher env" branches into the "lower branches"

**Comment by BrianZito** [comment]
My bad, I meant why do we need to be updating the unique together?

**Comment by tony-sappe** [comment]
> My bad, I meant why do we need to be updating the unique together?

https://github.com/fedspendingtransparency/usaspending-api/pull/1966

**Pull request merged**
