### PR TITLE
Tests for rm_submission of dependent TasProgramActivityObjectClassQua…

### PR DESCRIPTION
**Pull request by catherinedevlin**
…rterly

Tiny PR toward verifying fix of DS-1110.

### CODE REVIEW

**Comment by afrasier** [comment]
Did you mean to add that model to the SUBMISSION_MODELS which it checks to validate are 0 counts after deletion?

**Comment by catherinedevlin** [comment]
Oh, of course!  Thanks for catching that, @afrasier/

**Comment by bsweger** [comment]
Good call, @catherinedevlin! Do you think we should also add `AppropriationAccountBalancesQuarterly` to the list of things to check?

**Comment by catherinedevlin** [comment]
A good suggestion, @bsweger  - incorporated.

**Pull request merged**
